### ISSUE TITLE
Turn off console logging

### ISSUE THREAD

**Issue by tkserver** [tamilvasan/angularjs-application-insights-v2#1]
Thanks for the repo. It's working great. Just wondering how to turn off the logging in the console.

**Comment by nazrdogan** [comment]
I checked code  ```enableDebug``` option can turn off.
[https://github.com/tamilvasan/angularjs-application-insights-v2/blob/e8483d20eb6baf5ef4f7f69bd8f83d3a82b514a1/src/ApplicationInsightsModule.ts#L87](here)

**Comment by tamilvasan** [comment]
Thanks @nazrdogan for your answer. I am closing this issue.
