### ISSUE TITLE
$provide.decorator breaks our unit tests

### ISSUE THREAD

**Issue by tkserver** [tamilvasan/angularjs-application-insights-v2#2]
Is the section around line 78 necessary for this to function?  $provide.decorator('$log'..... breaks our unit tests/logging. 

Thanks!

**Comment by tamilvasan** [comment]
It is an additional feature through which you can forward all **$log** entries to Application Insights without writing separate track* API calls. You can disable it by setting false to **config.autoLogTracking**.
